jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v3

      - name: Set Git Config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Add Public Remote and Push
        run: |
          git remote add public https://$PUBLIC_REPO_TOKEN@github.com/pritish384/Algo-Trading-Excel-Fyers.git
          git push public main --force
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
